### ISSUE TITLE
Which git workflow are you using?

### ISSUE THREAD

**Issue by cwickham** [OSUCliMates/CliMates#4]
Here's my best outline of three possible git workflows you could use for this project.  It sounds like you have started down the *Forking Workflow* which suggests you should probably stick with it (?), but it's worth double checking now, since it is probably the most complicated workflow, that everyone is on board.  

Feel free to ask questions, make comments here.  

## Forking Workflow

Everyone has their own fork of the main repo.  You do your work locally on a branch of your fork of the main repo.  To get your work into the main repo, you initiate a Pull Request.

**Pros:**
* Using Pull Requests means you can review changes before pulling them into the main repo.
* You can limit who has permission to change the main repo.
* This is the workflow most open-source projects use, so learning it means you'll also learn how to contribute to other projects.

**Cons:**
* It's the most complicated because there are more repos involved.
* It's more work to keep your fork up-to-date with the main repo.

## Branching Workflow

Everyone works in the main repo on their own branches.  You do your work locally in a branch of a clone of the main repo.  To get your work into the main repo, you initiate a Pull Request.

**Pros:**
* Using Pull Requests means you can review changes before pulling them into the main repo.
* It's easy to switch to someone else's branch to see their work, and/or push your suggestions to their branch.

**Cons:**
* It is easier to push to someone else's branch or the master branch accidentally.

## Centralised Workflow

Everyone works in the main repo on the `master` branch.  You do your work locally in the master branch of a clone of the main repo.  To get your work into the main repo, you push to the repo.

**Pros:**
* Easiest to set up

**Cons:**
* No pull requests, so harder to review changes before integrating them
* Messier commit history
* Harder to control *when* you deal with merge conflicts

**Comment by jimmylovestea** [comment]
This is amazing @cwickham ! When I setup Rstudio/Git to work on the project, I used the Branching Workflow since that was what I'm most familiar with already. But I'd be up for utilizing the Forking Workflow if other people are hip to learn the defacto standard in OS.
